import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { wrap } from "@/server/lib/http";
import { requireSession } from "@/server/lib/auth";
import { explainIncident } from "@/server/services/ai/incident-explain";

const Query = z.object({
  // Bounded to prevent abuse — incident descriptions are short.
  desc: z.string().min(1).max(200),
});

export const dynamic = "force-dynamic";
export const maxDuration = 15;

// Auth-gated (anon device session qualifies) like the other /api/ai
// endpoints. Per-IP middleware cap and the process-local LRU in the
// service further constrain cost.
export const GET = wrap(async (req: NextRequest) => {
  requireSession(req);
  const { desc } = Query.parse(Object.fromEntries(req.nextUrl.searchParams));
  const out = await explainIncident(desc);
  return NextResponse.json({
    explanation: out.explanation,
    cached: out.cached,
    aiConfigured: out.aiConfigured,
    disclaimer:
      "Plain-language definition of the offense category, generated by AI. " +
      "Does not describe what specifically happened in this report.",
  });
});
