#!/usr/bin/env node
// Generates Sources/Core/Cities.generated.swift from the API's own city
// registry (packages/crime-data). The native app resolves "which city am I
// in?" fully OFFLINE from these bounding boxes, so the registry must not
// drift from the server that scores those same slugs.
//
// Run: node apps/ios/tools/gen-cities.mjs
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../../..");
const { CITIES } = await import(resolve(repo, "packages/crime-data/dist/cities.js"));

const rows = CITIES.map((c) => {
  const b = c.bbox;
  const esc = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `    City(slug: "${esc(c.slug)}", label: "${esc(c.label)}", ` +
    `south: ${b.south}, west: ${b.west}, north: ${b.north}, east: ${b.east}),`;
}).join("\n");

const swift = `// Generated by apps/ios/tools/gen-cities.mjs — DO NOT EDIT BY HAND.
// Source of truth: packages/crime-data/src/cities.ts (${CITIES.length} cities).
import CoreLocation
import Foundation

/// A jurisdiction CommunitySafe scores, with the bounding box used to decide
/// which city a coordinate belongs to without a network round-trip.
struct City: Identifiable, Hashable, Sendable {
    let slug: String
    let label: String
    let south: Double
    let west: Double
    let north: Double
    let east: Double

    var id: String { slug }

    var center: CLLocationCoordinate2D {
        CLLocationCoordinate2D(latitude: (south + north) / 2, longitude: (west + east) / 2)
    }

    func contains(_ c: CLLocationCoordinate2D) -> Bool {
        c.latitude >= south && c.latitude <= north && c.longitude >= west && c.longitude <= east
    }
}

enum CityRegistry {
    /// Alphabetical by label so pickers read naturally.
    static let all: [City] = [
${rows}
    ].sorted { $0.label.localizedCaseInsensitiveCompare($1.label) == .orderedAscending }

    static func city(slug: String) -> City? { all.first { $0.slug == slug } }

    /// Nearest covered city to a coordinate. Prefers a bounding-box hit; falls
    /// back to the closest centre so a user outside every covered city still
    /// lands somewhere sensible instead of on a hardcoded default.
    static func nearest(to c: CLLocationCoordinate2D) -> City? {
        if let hit = all.first(where: { $0.contains(c) }) { return hit }
        let here = CLLocation(latitude: c.latitude, longitude: c.longitude)
        return all.min { a, b in
            here.distance(from: CLLocation(latitude: a.center.latitude, longitude: a.center.longitude))
                < here.distance(from: CLLocation(latitude: b.center.latitude, longitude: b.center.longitude))
        }
    }

    /// True when the coordinate actually falls inside a covered city — used to
    /// tell the user "we don't cover here yet" rather than silently showing a
    /// distant city's grade as if it were theirs.
    static func isCovered(_ c: CLLocationCoordinate2D) -> Bool {
        all.contains { $0.contains(c) }
    }
}
`;

const outDir = resolve(here, "../Sources/Core");
writeFileSync(resolve(outDir, "Cities.generated.swift"), swift);
console.log(`Wrote ${CITIES.length} cities -> Sources/Core/Cities.generated.swift`);
