// Generated by apps/ios/tools/gen-cities.mjs — DO NOT EDIT BY HAND.
// Source of truth: packages/crime-data/src/cities.ts (57 cities).
import CoreLocation
import Foundation

/// A jurisdiction CommunitySafe scores, with the bounding box used to decide
/// which city a coordinate belongs to without a network round-trip.
struct City: Identifiable, Hashable, Sendable {
    let slug: String
    let label: String
    let south: Double
    let west: Double
    let north: Double
    let east: Double

    var id: String { slug }

    var center: CLLocationCoordinate2D {
        CLLocationCoordinate2D(latitude: (south + north) / 2, longitude: (west + east) / 2)
    }

    func contains(_ c: CLLocationCoordinate2D) -> Bool {
        c.latitude >= south && c.latitude <= north && c.longitude >= west && c.longitude <= east
    }
}

enum CityRegistry {
    /// Alphabetical by label so pickers read naturally.
    static let all: [City] = [
    City(slug: "san-diego", label: "San Diego", south: 32.53, west: -117.3, north: 33.1, east: -116.9),
    City(slug: "los-angeles", label: "Los Angeles", south: 33.7, west: -118.67, north: 34.34, east: -118.15),
    City(slug: "san-francisco", label: "San Francisco", south: 37.7, west: -122.55, north: 37.83, east: -122.35),
    City(slug: "chicago", label: "Chicago", south: 41.64, west: -87.94, north: 42.02, east: -87.52),
    City(slug: "seattle", label: "Seattle", south: 47.5, west: -122.46, north: 47.74, east: -122.22),
    City(slug: "new-york", label: "New York City", south: 40.49, west: -74.27, north: 40.92, east: -73.68),
    City(slug: "colorado-springs", label: "Colorado Springs", south: 38.7, west: -104.92, north: 39.1, east: -104.55),
    City(slug: "detroit", label: "Detroit", south: 42.25, west: -83.29, north: 42.45, east: -82.91),
    City(slug: "washington-dc", label: "Washington", south: 38.79, west: -77.12, north: 38.99, east: -76.91),
    City(slug: "boston", label: "Boston", south: 42.23, west: -71.19, north: 42.4, east: -70.99),
    City(slug: "philadelphia", label: "Philadelphia", south: 39.87, west: -75.28, north: 40.14, east: -74.96),
    City(slug: "oakland", label: "Oakland", south: 37.69, west: -122.36, north: 37.89, east: -122.11),
    City(slug: "cincinnati", label: "Cincinnati", south: 39.05, west: -84.72, north: 39.22, east: -84.36),
    City(slug: "new-orleans", label: "New Orleans", south: 29.86, west: -90.14, north: 30.07, east: -89.62),
    City(slug: "baton-rouge", label: "Baton Rouge", south: 30.3, west: -91.27, north: 30.59, east: -91),
    City(slug: "cambridge", label: "Cambridge", south: 42.34, west: -71.16, north: 42.41, east: -71.07),
    City(slug: "dallas", label: "Dallas", south: 32.6, west: -97.01, north: 33.04, east: -96.45),
    City(slug: "charlotte", label: "Charlotte", south: 35, west: -81, north: 35.4, east: -80.62),
    City(slug: "baltimore", label: "Baltimore", south: 39.197, west: -76.711, north: 39.372, east: -76.529),
    City(slug: "minneapolis", label: "Minneapolis", south: 44.89, west: -93.33, north: 45.05, east: -93.19),
    City(slug: "cleveland", label: "Cleveland", south: 41.39, west: -81.97, north: 41.61, east: -81.53),
    City(slug: "milwaukee", label: "Milwaukee", south: 42.92, west: -88.07, north: 43.2, east: -87.83),
    City(slug: "las-vegas", label: "Las Vegas", south: 35.99, west: -115.4, north: 36.4, east: -114.95),
    City(slug: "boise", label: "Boise", south: 43.5, west: -116.4, north: 43.75, east: -116.05),
    City(slug: "buffalo", label: "Buffalo", south: 42.83, west: -78.92, north: 42.97, east: -78.79),
    City(slug: "norfolk", label: "Norfolk", south: 36.79, west: -76.34, north: 36.97, east: -76.18),
    City(slug: "kansas-city", label: "Kansas City", south: 38.85, west: -94.78, north: 39.3, east: -94.4),
    City(slug: "saint-paul", label: "Saint Paul", south: 44.87, west: -93.22, north: 45.01, east: -93),
    City(slug: "pittsburgh", label: "Pittsburgh", south: 40.36, west: -80.1, north: 40.5, east: -79.86),
    City(slug: "fort-worth", label: "Fort Worth", south: 32.55, west: -97.54, north: 32.96, east: -97.03),
    City(slug: "denver", label: "Denver", south: 39.61, west: -105.11, north: 39.91, east: -104.6),
    City(slug: "sacramento", label: "Sacramento", south: 38.437, west: -121.56, north: 38.685, east: -121.362),
    City(slug: "atlanta", label: "Atlanta", south: 33.647, west: -84.551, north: 33.887, east: -84.29),
    City(slug: "indianapolis", label: "Indianapolis", south: 39.632, west: -86.329, north: 39.928, east: -85.937),
    City(slug: "honolulu", label: "Honolulu", south: 21.245, west: -158.29, north: 21.711, east: -157.648),
    City(slug: "long-beach", label: "Long Beach", south: 33.733, west: -118.249, north: 33.885, east: -118.063),
    City(slug: "phoenix", label: "Phoenix", south: 33.29, west: -112.32, north: 33.92, east: -111.93),
    City(slug: "jacksonville", label: "Jacksonville", south: 30.1, west: -81.9, north: 30.58, east: -81.39),
    City(slug: "virginia-beach", label: "Virginia Beach", south: 36.68, west: -76.23, north: 36.94, east: -75.91),
    City(slug: "gainesville", label: "Gainesville", south: 29.58, west: -82.45, north: 29.72, east: -82.2),
    City(slug: "tampa", label: "Tampa", south: 27.81, west: -82.62, north: 28.17, east: -82.27),
    City(slug: "nashville", label: "Nashville", south: 35.97, west: -87.06, north: 36.41, east: -86.51),
    City(slug: "houston", label: "Houston", south: 29.52, west: -95.91, north: 30.11, east: -95.01),
    City(slug: "montgomery-county", label: "Montgomery County", south: 38.93, west: -77.44, north: 39.31, east: -76.89),
    City(slug: "prince-georges-county", label: "Prince George's County", south: 38.54, west: -77.08, north: 39.13, east: -76.67),
    City(slug: "dayton", label: "Dayton", south: 39.67, west: -84.34, north: 39.85, east: -84.12),
    City(slug: "rochester", label: "Rochester", south: 43.05, west: -77.74, north: 43.24, east: -77.49),
    City(slug: "raleigh", label: "Raleigh", south: 35.69, west: -78.78, north: 35.94, east: -78.49),
    City(slug: "grand-rapids", label: "Grand Rapids", south: 42.88, west: -85.75, north: 43.02, east: -85.58),
    City(slug: "riverside", label: "Riverside", south: 33.86, west: -117.52, north: 34.02, east: -117.27),
    City(slug: "savannah", label: "Savannah", south: 31.96, west: -81.25, north: 32.18, east: -81.04),
    City(slug: "corpus-christi", label: "Corpus Christi", south: 27.63, west: -97.55, north: 27.85, east: -97.27),
    City(slug: "salt-lake-city", label: "Salt Lake City", south: 40.7, west: -112.1, north: 40.86, east: -111.78),
    City(slug: "hartford", label: "Hartford", south: 41.71, west: -72.72, north: 41.81, east: -72.64),
    City(slug: "wichita", label: "Wichita", south: 37.58, west: -97.5, north: 37.79, east: -97.18),
    City(slug: "tucson", label: "Tucson", south: 32.06, west: -111.1, north: 32.32, east: -110.71),
    City(slug: "albuquerque", label: "Albuquerque", south: 34.95, west: -106.79, north: 35.22, east: -106.47),
    ].sorted { $0.label.localizedCaseInsensitiveCompare($1.label) == .orderedAscending }

    static func city(slug: String) -> City? { all.first { $0.slug == slug } }

    /// Nearest covered city to a coordinate. Prefers a bounding-box hit; falls
    /// back to the closest centre so a user outside every covered city still
    /// lands somewhere sensible instead of on a hardcoded default.
    static func nearest(to c: CLLocationCoordinate2D) -> City? {
        if let hit = all.first(where: { $0.contains(c) }) { return hit }
        let here = CLLocation(latitude: c.latitude, longitude: c.longitude)
        return all.min { a, b in
            here.distance(from: CLLocation(latitude: a.center.latitude, longitude: a.center.longitude))
                < here.distance(from: CLLocation(latitude: b.center.latitude, longitude: b.center.longitude))
        }
    }

    /// True when the coordinate actually falls inside a covered city — used to
    /// tell the user "we don't cover here yet" rather than silently showing a
    /// distant city's grade as if it were theirs.
    static func isCovered(_ c: CLLocationCoordinate2D) -> Bool {
        all.contains { $0.contains(c) }
    }
}
